name: CI

on:
  pull_request:
  push:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml

  build:
    needs: lint
    uses: ./.github/workflows/_build.yml
